# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build = ENV["BUILD_NUMBER"]
    if !build.nil? && !build.empty?
      increment_build_number(build_number: build.to_i)
    end
    
    match(type: "appstore", readonly: is_ci, keychain_name: "login.keychain", keychain_password: "bark")

    build_app(workspace: "Bark.xcworkspace", scheme: "Bark")

    app_store_connect_api_key(
      key_id: "DX95H785DP",
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV("APP_STORE_CONNECT_KEY_CONTENT"),
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )    

    upload_to_testflight

    bark_key = ENV["BARK_KEY"]
    %x( curl https://api.day.app/#{bark_key}/Bark%20has%20completed%20processing )
    
  end
end
